<?php

namespace App\Notification;

use Twig\Environment;
use App\Entity\Contact;

class ContactNotification {

    private $twig;
    private $mailer;
    public function __construct(\Swift_Mailer $mailer, Environment $twig){
        $this->twig = $twig;
        //$transport = (new \Swift_SmtpTransport('smtp.mailtrap.io', 2525))
        //            ->setUsername('6fcdcd3b5adc4b') // generated by Mailtrap
        //            ->setPassword('7bf7f55e5824f6'); // generated by Mailtrap
       // dump($mailer);
       // die();
       // $transport = (new \Swift_SmtpTransport('smtp.gmail.com', 465, "ssl"))
       //             ->setUsername('mathieuchris38@gmail.com') // generated by Mailtrap
       //             ->setPassword('Mathieu1993'); // generated by Mailtrap
       //             $transport->setStreamOptions(array('ssl' => array('allow_self_signed' => true, 'verify_peer' => false, 'verify_peer_name' => false)));
        //$this->mailer = new \Swift_Mailer($transport);
        $transport = $mailer->getTransport();
        if($transport instanceof \Swift_Transport_EsmtpTransport){
            $transport->setStreamOptions([
                'ssl' => ['allow_self_signed' => true, 'verify_peer' => false, 'verify_peer_name' => false]
            ]);
        }
        $this->mailer = $mailer;
    }
    public function notify(Contact $contact) {
        //dump($this->mailer);
        //die();
        $headers = 'From: info-dadch@dadch-co.com' . "\n";
        $headers .= 'Reply-To: info-dadch@dadch-co.com' . "\n";
        $headers .= 'Content-Type: text/html; charset="utf-8"' . "\n";
        $headers .= 'Content-Transfer-Encoding: 8bit';
        $emailsEnvoyesAvecSucces = mail(
            'info-dadch@dadch-co.com',
            'dadch-co.com :'.$contact->getSujet(),
            $this->twig->render('emails/contact.html.twig', ['contact' => $contact]),
            $headers);
        
        $headers = 'From: info-dadch@dadch-co.com' . "\n";
        $headers .= 'Reply-To: info-dadch@dadch-co.com' . "\n";
        $headers .= 'Content-Type: text/html; charset="utf-8"' . "\n";
        $headers .= 'Content-Transfer-Encoding: 8bit';
        $emailsEnvoyesAvecSucces = mail(
            $contact->getEmail(),
            'Dadch&Co Market Research Agency',
            $this->twig->render('emails/confirmation.html.twig', ['contact' => $contact]),
            $headers);
    }
}